openapi: 3.0.1
info:
  title: Calendar-Booking API
  description: A platform for managing/reserving items such as sports courts, meeting rooms, and other resources.
  version: 1.0.0
servers:
- url: http://localhost:5000
tags:
- name: facilities
  description: Facilities
- name: auth
  description: Authentication / Authorization
paths:
  /api/facilities/{id}:
    get:
      tags:
      - facilities
      description: Gets information about a facility
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: Numeric ID of the facility
      responses:
        200:
          description: An object containing info about the facility
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Facility'

  /api/auth/signup:
    post:
      tags:
      - auth
      description: Creates a new user
      requestBody:
        content:
          application/json:
            schema:
              required:
              - email
              - password
              properties:
                email:
                  type: string
                password:
                  type: string
        required: true
      responses:
        201:
          description: Returns the new user_id.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NewUser'

components:
  schemas:
    Facility:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        description:
          type: string
    NewUser:
      type: object
      properties:
        user_id:
          type: integer